<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHx7jTZZ\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHx7jTZZ/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerHx7jTZZ.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerHx7jTZZ\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerHx7jTZZ\appAppKernelProdContainer([
    'container.build_hash' => 'Hx7jTZZ',
    'container.build_id' => 'cc3aeab2',
    'container.build_time' => 1769501630,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHx7jTZZ');
