version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: prestashop_db_23U2729
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./prestashop_app/mysql:/var/lib/mysql
    networks:
      - prestashop_network
    command: --default-authentication-plugin=mysql_native_password

  prestashop:
    image: prestashop/prestashop:latest
    container_name: prestashop_app_23U2729
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DB_SERVER=db
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWD=${MYSQL_PASSWORD}
      - PS_DOMAIN=${PS_DOMAIN}
      - PS_FOLDER_ADMIN=${PS_FOLDER_ADMIN}
      - PS_FOLDER_INSTALL=${PS_FOLDER_INSTALL}
      - PS_LANGUAGE=${PS_LANGUAGE}
      - PS_COUNTRY=${PS_COUNTRY}
      - PS_INSTALL_AUTO=${PS_INSTALL_AUTO}
      - ADMIN_MAIL=${ADMIN_MAIL}
      - ADMIN_PASSWD=${ADMIN_PASSWORD}
    volumes:
      - ./prestashop_app/prestashop:/var/www/html
    ports:
      - "5780:80"
    networks:
      - prestashop_network

networks:
  prestashop_network:
    driver: bridge
