services:
  db:
    image: mariadb:10.11
    container_name: prestashop_db_23U2729
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root123456
      MARIADB_DATABASE: prestashop
      MARIADB_USER: prestashop
      MARIADB_PASSWORD: prestashop123
    volumes:
      - ./prestashop_app/mysql:/var/lib/mysql
    networks:
      - prestashop_network

  prestashop:
    image: prestashop/prestashop:8.1
    container_name: prestashop_app_23U2729
    restart: unless-stopped
    environment:
      DB_SERVER: db
      DB_NAME: prestashop
      DB_USER: prestashop
      DB_PASSWD: prestashop123
      PS_INSTALL_AUTO: 0
      PS_DOMAIN: 23U2729.systeme-res30.app
    volumes:
      - ./prestashop_app/prestashop:/var/www/html
    ports:
      - "5780:80"
    networks:
      - prestashop_network
    depends_on:
      - db

networks:
  prestashop_network:
    driver: bridge
